# Generated by Django 5.0.1 on 2025-02-27 22:31

import django.contrib.postgres.fields
import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=100)),
                ('image_file', models.ImageField(height_field='height', upload_to='thumbnails/', width_field='width')),
                ('width', models.PositiveSmallIntegerField(default=1280, editable=False)),
                ('height', models.PositiveSmallIntegerField(default=720, editable=False)),
            ],
            options={
                'verbose_name': 'Thumbnail',
                'verbose_name_plural': 'Thumbnails',
            },
        ),
        migrations.CreateModel(
            name='CompletedSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.PositiveIntegerField()),
                ('completed', models.PositiveIntegerField()),
                ('completed_on', models.DateField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('UN', 'Unassigned'), ('BA', 'Basic'), ('MO', 'Moderate'), ('IN', 'Intermediate'), ('AD', 'Advanced')], default='UN', max_length=2)),
                ('instructions', django_jsonform.models.fields.JSONField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='fitness.activitycategory')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.activitythumbnail')),
            ],
            options={
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('weekday', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), default=list, size=None)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('UN', 'Unassigned'), ('BA', 'Basic'), ('MO', 'Moderate'), ('IN', 'Intermediate'), ('AD', 'Advanced')], default='UN', max_length=2)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='fitness.activitycategory')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.activitythumbnail')),
            ],
            options={
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), default=list, size=None)),
                ('exact_dates', django_jsonform.models.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, size=None)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.workout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(through='fitness.WorkoutExercise', to='fitness.exercise'),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('time', models.DurationField(blank=True, null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('until_failure', models.BooleanField(default=False, verbose_name='until failure')),
                ('weight_level', models.CharField(choices=[('UN', 'Unspecified'), ('LI', 'Light'), ('MO', 'Moderate'), ('HE', 'Heavy'), ('MA', 'Maximum')], default='UN', max_length=2)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.workoutexercise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_recordings', django_jsonform.models.fields.JSONField()),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fitness.workoutexercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client')),
                ('workouts', models.ManyToManyField(through='fitness.WorkoutAssignment', to='fitness.workout')),
            ],
        ),
        migrations.AddField(
            model_name='workoutassignment',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.workoutplan'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client')),
                ('completed_exercises', models.ManyToManyField(through='fitness.SessionExercise', to='fitness.workoutexercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fitness.workout')),
            ],
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.workoutsession'),
        ),
    ]
